### ISSUE TITLE
Bestiary not loading when opening compendium

### ISSUE THREAD

**Issue by Ssherlockhemlock** [Jax-PF2/9405lkllkdfjgd23a#1]
I've disabled all modules except spellcasters and have the most up to date or both.  When I open the compendium it says 

Compendium "jam-and-jax-npc-index-spellcasters.sorc" could not be loaded. This goes for the others such as wizard and druid too.

It also seems to be doing the same thing in the Warriors and Smoke and Sail modules.

Compendium "jam-and-jax-npc-index-warriors.rangers" could not be loaded. As well as

main.bundle.js:1 Actor 'Hardy Mercenary lvl 1' does not have all required data fields. Consider unselecting pack 'Jam and Jax NPC Fighters' in the compendium browser settings.

**Comment by Jax-PF2** [comment]
Hi Sherlock,

Sorry I didn't see this email. Are you still have troubles? I just curious
before I try to problem solve it.  Are you updated to newest versions of
Foundry and the PF2 system?

--Jax

**Comment by Ssherlockhemlock** [comment]
﻿
Hello, thanks for getting back to me.

Yeah I’m still having the issue, I’ve updated everything including the recent Warriors update though the Ranger from it still isn’t working. The Smoke and Sails, Spellcasters and Ancestries modules still aren’t working either. I’ve found a workaround for it anyway, it’s just a matter of importing the content then making new compendiums for them.

On 4 Nov 2022, at 02:48, Jax-PF2 ***@***.***> wrote:

﻿

Hi Sherlock,

Sorry I didn't see this email. Are you still have troubles? I just curious
before I try to problem solve it. Are you updated to newest versions of
Foundry and the PF2 system?

--Jax

**Comment by Jax-PF2** [comment]
I'm really sorry that is happening for you.  Let me know your email for
pathfinder infinite, I will give you $20 back as an apology for the hassle,
which you could keep in your account for future purchases or redeem via
paypal.

I will try to problem solve this.  I'm not sure if I can solve it because I
am not an expert, and no one else has had  this problem (or at least told
me about it) so I am not exactly sure what the problem might be.

What type of server are you using?  (self-hosted, Foundry, something else?)

--Jax

**Comment by Jax-PF2** [comment]
You know what I can do is also email or google drive share you the files
directly which you can put into your module folder (easy if you are
self-hosting)

--Jax

**Comment by Ssherlockhemlock** [comment]
No it’s fine honestly I don’t want a refund, the modules still good and I want to support smaller content creators but thank you for the offer anyway. Like I said I can still get it to work and I can still open the compendiums it’s just they don’t load in the browser.

I’m self hosting on foundry, I’ve not seen anyone else with the issue so it might just be something wrong on my end. If you can’t find the problem it’s no big deal really I just thought I’d log the issue in case it pops up for someone else.

On 4 Nov 2022, at 13:13, Jax-PF2 ***@***.***> wrote:

﻿

You know what I can do is also email or google drive share you the files
directly which you can put into your module folder (easy if you are
self-hosting)

--Jax

**Comment by Jax-PF2** [comment]
Would a zip of the files from the modules interest you for direct placement
into your module folder, or is that redundant with what you are able to
already get?
--Jax

**Comment by Ssherlockhemlock** [comment]
I wouldn’t mind if you’re making the offer, might solve it. Like I say it’s not a massive issue, mostly just a matter of convenience. Also don’t worry about me sharing the files if you do send them, promise I won’t.

On 4 Nov 2022, at 15:54, Jax-PF2 ***@***.***> wrote:

﻿

Would a zip of the files from the modules interest you for direct placement
into your module folder, or is that redundant with what you are able to
already get?
--Jax

**Comment by Jax-PF2** [comment]
Why don't you email me directly using the email in the Warriors Foundry PDF
and I'll send you some files.
